# Generated by Django 4.2.3 on 2023-07-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
